camera1:
    camera:
      ros__parameters:
        device_type: 'd455'
        serial_no: ''
        usb_port_id: ''

        config_file: "config/camera-depth-filter-settings.json"

        depth_fps: 10.0
        depth_width: 848
        depth_height: 480
        depth_qos: "SENSOR_DATA"

        infra_fps: 10.0
        infra_width: 848
        infra_height: 480
        infra_qos: "SENSOR_DATA"

        enable_accel: false
        enable_color: false
        enable_depth: true
        enable_gyro: false
        enable_infra1: true
        enable_infra2: false
        enable_pointcloud: false

        filters: ''

        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR

        stereo_module:
          emitter_enabled: true
        unite_imu_method: ''

        rosbag_filename: ''
